### PR TITLE
React 0.14

### PR DESCRIPTION
**Pull request by luxflux**
These changes were necessary to get it working with React 0.14.

### CODE REVIEW

**Comment by xeodou** [comment]
I am already work on support the react > 0.14, but i don't like `require('react/lib/emptyFunction');` i will push my change soon.

**Comment by luxflux** [comment]
Okay, looking forward to your changes!

**Comment by xeodou** [comment]
Already fixed. I gonna close the PR. Thanks. @luxflux

**Comment by luxflux** [comment]
It works, thanks.

**Pull request closed without merging**
